name: PR Workflow

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Git User
        run: |
          git config --global user.name "${GITHUB_ACTOR}"
          git config --global user.email "${GITHUB_ACTOR}@users.noreply.github.com"

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Bump NPM
        run: |
          npm i -g npm@10
          npm i -g npm@11

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npx nx run-many -t build,test,lint,e2e

      - name: Deploy docs-site preview
        run: npx nx deploy docs-site
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DOCS_BASE_URL: /nx-github-pages/pr/${{ github.event.number }}/
